language: android
jdk:
    - oraclejdk7
android:
  components:
    - build-tools-22.0.1
    - android-22
    - extra-android-support
    - extra-android-m2repository
  licenses:
    - '.+'

before_install:
    - export JAVA7_HOME=/usr/lib/jvm/java-7-oracle
    - export JAVA_HOME=$JAVA8_HOME
script:
    - ./gradlew clean assemble check
